### ISSUE TITLE
Handle other detectors, starting with epixM

### ISSUE THREAD

**Issue by philiph-slac** [slaclab/beamtime-calibration-suite#57]
We currently just handle epixhr naturally.  Add epixM at a minimum before April beamtimes.

**Comment by nstelter-slac** [comment]
is this just a matter of changing calls like these, to be able to have input "epixM" instead?
```
self.det = self.myrun.Detector("epixhr")
        
return DataSource(exp=self.exp, run=run, intg_det="epixhr", max_events=self.maxNevents)
```

**Comment by philiph-slac** [comment]
I haven't looked carefully, but e.g. in psana2Base I have psana2Base.py:        self.detRows = 288
which is not universal.  We do have
AnalyzeH5.py:        parser.add_argument('-d', '--detType', type=str, default='', help='Epix100, Epix10ka, Epix10kaQuad, Epix10ka2M, ...')
and
basicSuiteScript.py:            if args.nModules is not None:
basicSuiteScript.py:                self.detType = self.ePix10k_cameraTypes[args.nModules]

It might be good to maintain a class that knows these sorts of things to keep them out of the way.

**Comment by philiph-slac** [comment]
The suiteConfig might be a good place to put the default for this while we're focusing on one sort of detector as you say.

**Comment by philiph-slac** [comment]
One idea might be for the suite scripts to have a DetInfo or DetAttribute class.  E.g. in pseudo pseudocode:

class DetInfo(object):
    def __init___(self, detType):
        self.detType = detType
        ## initialize members to None or whatever
    self.knownTypes = ['epixhr', 'epixM', 'rixsCCD']
     if self.detType not in self.knownTypes:
         raise Exception, "type %s not in known types" %(self.detType), knownTypes
       if self.detType == 'epixhr':
           self.setup_epixhr()
      elif self.detType == 'rixsCCD':
...

   def setup_epixhr(self, version=0):
       self.nRows = 288
       self.nCols = 666
       self.gainMode = self.getGainMode()
       self.preferredCommonMode = 'regionCommonMode'
       self.clusterShape = [3,3]


   def setup_rixsCCD(self, version=0):
       self.dimension = self.getDimension()##1d or 2d
       if self.dimension == '1d':
          self.nRows = foo
...

**Comment by nstelter-slac** [comment]
seems like good idea to me!

is there any page listing what value we need to set for each detector?

**Comment by philiph-slac** [comment]
Various detector people will come along and fill this information in.  If you could set up a good skeleton class that would be great.  I don't know for example if it would be cleanest to have an ePixM class which inherits from a PlainDetector class (not that name) or as above.
