### ISSUE TITLE
After epixM is stable, ruff code base

### ISSUE THREAD

**Issue by philiph-slac** [slaclab/beamtime-calibration-suite#72]
Low priority but @nstelter-slac is in favor.  At least evaluate the effort by doing one file.

**Comment by nstelter-slac** [comment]
just dumping some thoughts:

ruff (https://github.com/astral-sh/ruff) is a tool to lint and auto-format the code
can automatically fix many issues without changing functionality of code, but will still be alot of errors to fix manually

another tool could use is pylint (https://github.com/pylint-dev/pylint) which catches some stuff ruff doesn't 

we could have a script like 'lint.sh' that we can run before commit or just occasionally that executes ruff and/or pylint linting and auto-formatting

setting things up is quick, but the biggest time sink will be fixing all the current issues the linting finds (and cant auto-fix), but subsequent linting should be quick if we do it at a moderate frequently.

**Comment by nstelter-slac** [comment]
linting and formatting can be done by running
```
./lint_and_format.sh
```

**Comment by nstelter-slac** [comment]
linting and formatting can now be done by running

./lint_and_format.sh
